name: 💡 Feature Request
description: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Great ideas come from the community. Help us understand your use case and vision.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What's missing from the current system?
      placeholder: "I'm trying to accomplish X, but the current system doesn't support Y because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: What would you like to see implemented?
      placeholder: "I'd like to see a feature that..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 🏷️ Feature Category
      description: What type of feature is this?
      options:
        - Core Memory Operations
        - Analytics & ORC Support
        - User Experience & Setup
        - Integration & APIs
        - Performance Optimization
        - Documentation & Examples
        - Templates & Use Cases
        - Security & Privacy
        - Testing & Quality
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Priority Level
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my workflow"
        - "High - Would significantly improve my experience"
        - "Medium - Nice to have enhancement"
        - "Low - Minor improvement"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 📖 Use Case & Context
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I'm working on a project where...
        This feature would help me by...
        The impact would be...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternatives have you considered? What workarounds are you currently using?
      placeholder: |
        I've tried...
        The workaround I'm using is...
        This doesn't work well because...

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        This could work by...
        It might require changes to...
        Potential challenges might be...

  - type: checkboxes
    id: impact
    attributes:
      label: 📊 Expected Impact
      description: What areas would this feature impact? (Select all that apply)
      options:
        - label: Memory system performance
        - label: User experience and ease of use
        - label: Integration with existing workflows
        - label: Analytics and insights capabilities
        - label: Multi-project support
        - label: Team collaboration features
        - label: Data security and privacy
        - label: Documentation and examples

  - type: textarea
    id: examples
    attributes:
      label: 🎯 Example Usage
      description: Show us how you'd use this feature
      placeholder: |
        ```bash
        # Example command or workflow
        claude-memory --your-feature-here
        ```
        
        Or describe the workflow in detail...
      render: markdown

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can provide additional use cases and requirements
        - label: I can help with documentation
        - label: I'm just suggesting the idea

  - type: textarea
    id: research
    attributes:
      label: 🔍 Additional Research
      description: Any relevant links, papers, or examples from other projects?
      placeholder: |
        Similar features in other projects:
        - Project X does Y by...
        
        Relevant resources:
        - Link to documentation/paper/example

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I searched existing issues and feature requests
          required: true
        - label: This is a feature request, not a bug report or question
          required: true
        - label: I've provided a clear use case and problem statement
          required: true
        - label: I've considered how this fits with the project's goals
          required: true

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Anything else you'd like to add?
      placeholder: Any additional context, mockups, or related information...

